language: ruby
env:
  global:
    - GIT_COMMITTER_NAME: "r7kamura"
    - GIT_COMMITTER_EMAIL: "r7kamura@gmail.com"
    - GIT_AUTHOR_NAME: "r7kamura"
    - GIT_AUTHOR_EMAIL: "r7kamura@gmail.com"
    - secure: "EmtA2mtXXFEtqzL/dlxmzL6dp7qh0hxSzVtfdqiadjW4PfXZsep0+mqiCEYmD+w1338oiQtgTtLagluGkdavIf74TvhIEgZ0KV4aFqvQ+x0v1Cu+m7egOdag7ZoLr0rHsJFiwa2hzM4SXecJMH++hHJ26RT0lGuFAx6CiKNMoY4="
script:
    - bundle exec middleman build
after_success:
    - cd build
    - git init
    - git add --all
    - git commit -m "Update from Travis CI"
    - 'git push https://$GITHUB_TOKEN@github.com/r7kamura/r7kamura.github.io.git master -f'
